# The below declaration is an example of how to set up an email account to be cleaned by 
# this automation process. You can set up as many accounts as needed by separating each 
# declaration with '[account_name]' in the beginning of each declaration. Currently only 
# gmail.com and abv.bg email accounts are tested/supported.

[config_name] -> put a unique name for the configuration  (Ex: test@gmail.com)
server: your email provider (Example: gmail.com)
account: your email account (Ex: test@gmail.com)
password: the password needed for the process to authenticate
max_messages: the number of maximum messages to clean in a single check, 10 by default
