* The below declaration is an example of how to set up an email account to be cleaned by 
this automation process. You can set up as many accounts as needed by separating each 
declaration with '---' in the beginning and the end. Currently only gmail.com and abv.bg 
email accounts are tested/supported.
---
Email Server or ES: your email provider (Example: gmail.com)
Arguments or Args: Account: your email account (Ex: test@gmail.com)
Args: Password: the password needed for the process to authenticate
Args: Max Messages: the number of maximum messages to clean in a single check, 10 by default
---
