# The below declaration is an example of how to set up an email account to be cleaned by 
# this automation process. You can set up as many accounts as needed by separating each 
# declaration with '[account_name]' in the beginning of each declaration. Currently only 
# gmail.com and abv.bg email accounts are tested/supported.

[config_name] -> put a unique name for the configuration  (Ex: test@gmail.com)
server: your email provider (Example: gmail.com)
email: your email account (Ex: test@gmail.com)
password: the password needed for the process to authenticate
max_messages: the number of maximum messages to clean in a single check, 10 by default
fetch_messages: whether to pull and return the messages
delete_messages: whether to delete the messages
# Pop specific options:
port: the port to use when connecting to the server - needed for the PopClient connections(abv.bg)
check_messages: prints the message format of the messages in the email box
# Imap specific options:
trash_folder: the folder where to copy messages marked for deletion
list_folders: prints the folder structure of the mail box
